### ISSUE TITLE
Add Details On How to Run

### ISSUE THREAD

**Issue by brettsaunders21** [refinedmods/sitegen#1]
Could you add a few details in the readme on how to run this / use it. 

I work on a small team who are creating a spigot plugin for Minecraft. Our website is becoming hard to manage and we wanted to test how you generate yours to create a new one for us.

Thanks in advance

**Comment by raoulvdberge** [comment]
You can use `sitegen build` or `sitegen watch`, with optional arguments:
`--output`: the output directory, by default `output/`
`--config`: the location of the config file, by default `site.json`

For examples on how the templating and config system works, check out https://github.com/refinedmods/website

**Comment by brettsaunders21** [comment]
Thank you for the help.

**Comment by raoulvdberge** [comment]
I'll leave this open so I remember to add this to the README.
